<template>
    <div class="privacy-policy">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 offset-md-1 col-md-10 offsetr-md-1 offset-xl-2 col-xl-8 offsetr-xl-2 offset-xxl-3 col-xxl-6 offsetr-xxl-3">
                    <div class="box">
                        <h1 class=" font-merel-bold c-blue text-center mb-3">Privacy Policy</h1>
                        <h4 class="font-merel-bold c-blue">Introduction and purpose</h4>
                        <p align="justify">
                        Luso Digital Assets carries out its activity in accordance with national
                        and international legislation to prevent and combat money laundering and
                        terrorist financing.
                        </p>
                        <p align="justify">
                        For this purpose, Luso Digital assets collects the personal data of its
                        users in strict compliance with the law and regardless of the value of the
                        amounts transacted. Data on the source and destination of the funds
                        transacted is also collected.
                        </p>
                        <p align="justify">
                        Luso Digital Assets is legally obliged to communicate to the competent
                        authorities any operation or activity considered suspicious, as well as to
                        fully cooperate with police and central authorities to detect indications
                        of the practice of any crimes.
                        </p>
                        <p align="justify">
                        This Privacy Notice applies to the processing activities performed by Luso
                        Digital Assets to the personal information of its clients and its potential
                        clients and website visitors.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Collection of your personal data
                        </h4>
                        <p>
                        In order to trade with us, you must first provide your name, email and
                        phone number, which we will use to send verification messages. Our ID
                        verification procedure uses a third-party software for document capture in
                        which we collect the following information:
                        </p>
                        <p style="margin-left: 100px;">
                            <ul style="list-style-type: disc;">
                                <li>Full name</li>
                                <li>Date of birth</li>
                                <li>Place of birth</li>
                                <li>Gender</li>
                                <li>Citizenship</li>
                            </ul>
                        </p>
                        <p align="justify">
                        After collecting this data, we will verify this information to make sure it
                        matches with your ID document such as a passport or Government-issued
                        identity card or Residence/Work permit.
                        </p>
                        <p align="justify">
                        We also collect technical data which includes browser and log information.
                        </p>
                        <p align="justify">
                        Browser Information – Information that is automatically collected via
                        analytics systems providers from your browser, including your IP address
                        and/or domain name and any external page that referred you to us, your
                        login information, browser type and version, time zone setting, browser
                        plug-in types and versions, operating system, and platform;
                        </p>
                        <p align="justify">
                        Log Information – Information that is generated by the use of Luso Digital
                        Assets platform that is automatically collected and stored in our server
                        logs. This may include, but is not limited to, device-specific information,
                        location information, system activity and any internal and external
                        information related to pages that you visit, including the full Uniform
                        Resource Locators (URL) clickstream to, through and from our Website or App
                        (including date and time; page response times, download errors, length of
                        visits to certain pages, page interaction information (such as scrolling,
                        clicks, and mouse-overs), and methods used to browse away from the page;
                        </p>
                        <p align="justify">
                        Other personal, commercial or identification information may be requested
                        since this policy does not limit the right of Luso Digital Assets to
                        request any further documents and/or information, if in our sole
                        discretion, we deem it’s necessary to comply with our legal obligations
                        under various anti-money laundering (AML) obligations, such as under the
                        European Union’s 5th AML directive.
                        </p>
                        <p align="justify">
                        We must verify your identity in order to accept you as our client and we
                        will use your personal data in order to effectively manage your trades with
                        us. This may include third parties carrying out identity checks on our
                        behalf. The use of your personal information is necessary for us to know
                        who you are, as we have a legal obligation to comply with “Know Your
                        Customer” and the customer due diligence regulatory obligations mentioned
                        previously.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Disclosure of your personal information
                        </h4>
                        <p align="justify">
                        We will not disclose any of its clients’ confidential information to a
                        third party, except: (a) to the extent that it is required to do so
                        pursuant to any applicable laws, rules or regulations; (b) if there is a
                        duty to disclose; (c) if our legitimate business interests require
                        disclosure; (d) in line with our Terms of Service; (e) at your request or
                        with your consent or to those described in this Privacy Notice. We will
                        endeavor to make such disclosures on a “need-to-know” basis, unless
                        otherwise instructed by a regulatory authority. Under such circumstances,
                        Luso Digital Assets will notify the third party regarding the confidential
                        nature of any such information.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Data security
                        </h4>
                        <p align="justify">
                        We have put in place appropriate security measures to prevent your personal
                        data from being accidentally lost, used, or accessed in an unauthorized
                        way, altered, or disclosed. In addition, we limit access to your personal
                        data to those employees and third parties who have a business need to know
                        such information. They will only process your personal data on our
                        instructions, and they are subject to a duty of confidentiality. We store
                        all data electronically in a secure manner to protect its confidentiality,
                        integrity and availability. Data is stored on servers which are protected
                        by actively maintained firewalls. We make use of up-to-date anti-virus
                        software and our servers have restricted access.
                        </p>
                        <p align="justify">
                        We cannot guarantee the security of information collected or transmitted
                        electronically however; we take reasonable care to safeguard your personal
                        information. However, we have put in place procedures to deal with any
                        suspected personal data breach and will notify you and any applicable
                        regulator of a breach where we are legally required to do so.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Data retention
                        </h4>
                        <p align="justify">
                        The personal data collected and processed by Luso Digital Assets will be
                        kept for the entire period in which the registration of your user is on our
                        website. You may, at any time, ask Luso Digital Assets to erase the
                        personal data that you have transmitted. In order to comply with certain
                        legal obligations, Luso Digital Assets processes personal data for a longer
                        period, such as the legal limitation period associated with the prevention
                        of money laundering and terrorist financing, which is 7 years.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Your legal rights
                        </h4>

                        <table cellspacing="0" cellpadding="16" class="table table-bordered">
                            <tbody>
                                <tr valign="top">
                                    <td><p lang="en-US" align="left"><strong>Legal right</strong></p></td>
                                    <td><p lang="en-US" align="left"><strong>Further information</strong></p></td>
                                </tr>
                                <tr valign="top">
                                    <td><p lang="en-US" align="left"><strong>Request access to your personal data</strong><em>
                                        (commonly known as a “data subject access request”)</em></p>
                                    </td>
                                    <td><p lang="en-US" align="left">
                                    This enables you to receive a copy of the personal data we
                                    hold about you and to check that we are lawfully processing
                                    it.</p>
                                    </td>
                                </tr>
                                <tr valign="top"><td><p lang="en-US" align="left"><strong>
                                    Request correction of the personal data we hold about
                                    you
                                    </strong></p></td><td><p lang="en-US" align="left">
                                    This enables you to have any incomplete or inaccurate data
                                    we hold about you corrected, though we may need to verify
                                    the accuracy of the new data you provide to us.</p></td>
                                </tr>
                                <tr valign="top"><td><p lang="en-US" align="left"><strong>Request erasure of your personal data</strong></p></td><td><p lang="en-US" align="left">
                                This enables you to ask us to delete or remove personal
                                data where there is no good reason for us continuing to
                                process it, subject to our legal and contractual
                                obligations.
                                </p><p lang="en-US" align="left">
                                You also have the right to ask us to delete or remove your
                                personal data where you have successfully exercised your
                                right to object to processing (see below), where we may
                                have processed your information unlawfully or where we are
                                required to erase your personal data to comply with local
                                law. Note, however, that we may not always be able to
                                comply with your request of erasure for specific legal
                                reasons which will be notified to you, if applicable, at
                                the time of your request.
                                </p></td>
                                </tr>
                                <tr valign="top"><td><p lang="en-US" align="left"><strong>Object to processing of your personal data</strong></p></td><td><p lang="en-US" align="left">
                                You can object to processing where we are relying on a
                                legitimate interest (or that of a third party), but you
                                feel such processing impacts your fundamental rights and
                                freedoms. However, you can not object to the processing
                                which is a legal obligation or where we must process your
                                information to satisfy a contract to which you are a party.
                                </p></td>
                                </tr>
                                <tr valign="top"><td><p lang="en-US" align="left"><strong>
                                    Request restriction of processing of your personal data
                                    </strong></p></td><td><p lang="en-US" align="left">
                                    This enables you to ask us to suspend the processing of
                                    your personal data in the following scenarios:
                                    </p><ul><li><p lang="en-US" align="left">
                                    if you want us to establish the data’s accuracy;
                                    </p></li><li><p lang="en-US" align="left">
                                    where our use of the data is unlawful, but you do
                                    not want us to erase it;
                                    </p></li><li><p lang="en-US" align="left">
                                    where you need us to hold the data even if we no
                                    longer require it as you need it to establish,
                                    exercise or defend legal claims; or
                                    </p></li><li><p lang="en-US" align="left">
                                    you have objected to our use of your data, but we
                                    need to verify whether we have overriding
                                    legitimate grounds to use it.
                                    </p></li></ul></td>
                                </tr>
                                <tr valign="top"><td><p lang="en-US" align="left"><strong>
                                    Request the transfer of your personal data to you or to
                                    a third party
                                    </strong></p></td><td><p lang="en-US" align="left">
                                    We will provide your personal data to you, or a third party
                                    you have chosen, in a structured, commonly used,
                                    machine-readable format.
                                    </p></td>
                                </tr>
                                <tr valign="top"><td><p lang="en-US" align="left"><strong>
                                    Withdraw consent at any time where we are relying on
                                    consent to process your personal data
                                    </strong></p></td><td><p lang="en-US" align="left">
                                    This will not affect the lawfulness of any processing
                                    carried out before you withdraw your consent. If you
                                    withdraw your consent, we may not be able to provide
                                    certain products or services to you. We will advise you if
                                    this is the case at the time you withdraw your consent.
                                    </p></td>
                                </tr>
                        </tbody>
                        </table>
                    
                        <h4 class="font-merel-bold c-blue">Reviews to the Policy</h4>
                        <p align="justify">
                        Our Privacy Policy is reviewed regularly to ensure that any new obligations
                        and technologies, as well as any changes to our business operations and
                        practices are taken into consideration, as well as that it remains abreast
                        of the changing regulatory environment. Any personal information we hold
                        will be governed by our most recent Privacy Policy.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Cookies
                        </h4>
                        <p align="justify">
                        When you use our products and services, we may make use of the standard
                        practice of placing tiny data files called cookies, flash cookies, pixel
                        tags, or other tracking tools (herein, “Cookies”) on your computer or other
                        devices used when engaging with us. We use Cookies to help us recognize you
                        as a customer, collect information about your use of our products and
                        services, to better customize our services and content for you, and to
                        collect information about your computer or other access devices to ensure
                        our compliance with our AML obligations.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Complaints
                        </h4>
                        <p align="justify">
                        If you have a complaint about this Policy or any element of how we use your
                        personal data, then please contact us first. If you are not satisfied and
                        are located in a European Union country, then please contact your local
                        data protection authority.
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Contact details
                        </h4>
                        <p align="justify">
                        We have appointed a representative who is responsible for overseeing
                        questions in relation to this Policy. If you have any questions about this
                        Policy, including any requests to exercise your legal rights, please
                        contact our Representative (as required pursuant to Article 27 of the
                        General Data Protection Regulation 2016/679 of the European Parliament) by
                        using the following e-mail address: madalena.catarino@lusodigitalassets.com
                        </p>
                        <h4 class="font-merel-bold c-blue">
                        Amends to the Privacy Policy
                        </h4>
                        <p>
                        Luso Digital Assets is entitled to the right to amend this policy whenever
                        should be necessary. Everything an amend takes place, the updated policy
                        will be duly published in our public website.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>

export default {
    name: 'PrivacyPolicy',
    
    data(){
        return{
        
        }
    },

    methods:{
        
    },

    computed: {
        
    },

    mounted(){
        
    }
}
</script>
<style scoped>
.c-blue {
    color: #2601cf;
}
p{
    margin-bottom: 25px;
    color: #888B8D;
    font-size: 18px;
}
.privacy-policy {
    padding: 100px;
}
.box {
    padding: 40px 60px;
    margin: 20px 0 20px;
    border-radius: 9px;
    background: #fff;
}
</style>

   